Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -14,7 +14,9 @@ on:
         # Default value if no value is explicitly provided
         default: 'World'
         # Input has to be provided for the workflow to run
-        required: true
+        required: true        
+      RELEASE_CANDIDATE_VERSION:
+        description: 'Release candidate'
 
 
 jobs:
@@ -22,11 +24,12 @@ jobs:
     runs-on: windows-2022
 
     steps:
-      - name: Run vcvars64.bat
-        shell: cmd
+      - name: Run pruebas
         run: |
-          echo El antiguo path es: %PATH% 
-          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat" 
-          echo El nuevo path es: %PATH% 
-          cl.exe /?
+          if (${{ github.event.inputs.RELEASE_CANDIDATE_VERSION }} -eq $null){
+            echo "You must specify the release candidate name!" > .error.log          
+            exit 1
+          }else{
+            echo "RELEASE_VERSION=${{ github.event.inputs.RELEASE_CANDIDATE_VERSION }}" 
+          }
 
